#!/bin/bash

# Set default directory for the path
[ -n $DOTFILE_PATH ] && export DOTFILE_PATH=${HOME}/.dotfile

# Source dependencies
for file in $(ls $DOTFILE_PATH/env); do
    source ${DOTFILE_PATH}/env/${file}
done

# Creates a file and puts an existing file into a backup directory
function newfile() {
    new_file=$1
    if [ -f $new_file ]; then
        backup_dir=$DOTFILE_PATH/data/backups
        mkdir -p $backup_dir >/dev/null 2>&1
        backup_file=$backup_dir/$(basename $new_file)_$(date | sed s/\ /_/g)
        echo -e "Moving original $new_file as: \n $backup_file\n"
        mv $new_file $backup_file
    fi
    touch $new_file
}

# Text that will be output to a fresh rc file.
# Contains the entry point to `dotfile.bash`
rcfile_autogen="
    ###########################################

    # This file was autogenerated by .dotfile :)
    # This file will call .dotfile entry script that will do all the magic

    # This is the path to .dotfile directory. It must be specified first
    DOTFILE_PATH=${HOME}/.dotfile

    # This line loads a pre-configured themes of your choice
    # Themes are stored in \$DOTFILE_PATH/themes
    theme=default2

    # Specify the plugins you wish to be loaded.
    # Array with '@' indicates you wish to load them all
    # Available plugins are stored in \$DOTFILE_PATH/plugins directory
    plugins=(@)
    
    # Source the entry point to .dotfile
    source $DOTFILE_PATH/dotfile.bash

    ###########################################
    
    # User settings:
    
"

function bash_setup()
{
    __linux && rcfile=${HOME}/.bashrc
    __macos && rcfile=${HOME}/.bash_profile
    new_file $rcfile
    echo $rcfile_autogen > $rcfile
}

function zsh_setup()
{
    rcfile=${HOME}/.zshrc
    new_file $rcfile
    echo $rcfile_autogen > $rcfile
}

bash_setup
setup_zsh

unset bash_setup zsh_setup new_file
