#!/bin/bash

# Set default directory for the path
[ -n $DOTFILE_PATH ] && export DOTFILE_PATH=${HOME}/.dotfile

source_env=${DOTFILE_PATH}/source_env.bash
source_login=${DOTFILE_PATH}/source_login.bash

# Creates a file and puts an existing file into a backup directory
function newfile() {
    new_file=$1
    if [ -f $new_file ]; then
        backup_path=$DOTFILE_PATH/data/backups/$(basename $new_file)_$(date | sed s/\ /_/g)
        echo "Moving original $new_file as $backup_path"
        mv $new_file $backup_path
    fi
    touch $new_file
}

# Appends 2..> arguments as lines of text to a file
function fprint() {
    file=$1
    shift
    echo "# File generated by 'dotfile'" >> $file
    for message in $@; do
        echo $message >> $file
    done
}

# This autogenerated text will be placed in non-interactive startup files
function env_msg() {
    file=$1
    fprint $file \
    "export DOTFILE_PATH=${DOTFILE_PATH}" \
    "#" \
    "source ${source_env}" \
    "#" \
    "#" \
    "#############################################" \
    "" \
    "# User settings:" \
    "#" \
    "#" \
    "#############################################"
}

# This autogenerated text will be placed in interactive startup files
function login_msg() {
    file=$1
    fprint $file \
    "# You can change themes to default ones in ${DOTFILE_PATH}/themes." \
    "# You can also add your own themes to ${DOTFILE_PATH}/themes/user." \
    "# Use theme filename as the value" \
    "#" \
    "theme=default" \
    "#" \
    "source ${source_login}" \
    "#" \
    "#" \
    "#############################################" \
    "#" \
    "# User settings:" \
    "#" \
    "#" \
    "#############################################"
}

function setup_bash() {
    env_file=${HOME}/.bashrc
    newfile $env_file
    fprint $env_file "export BASH_ENV=$env_file"
    env_msg $env_file
    # MacOS Terminal does not source .bashrc. It needs to be sourced in .bash_profile in the beginning
    if [ -f ${HOME}/.bash_profile ]; then
        login_file=${HOME}/.bash_profile
    else
        if __linux; then
            login_file=${HOME}/.profile
        elif __macos; then
            touch ${HOME}/.bash_profile
            login_file=${HOME}/.bash_profile
        fi
    fi
    newfile $login_file
    if __macos; then
        fprint $login_file "[ -f ${HOME}/.bashrc ] && source ${HOME}/.bashrc"
    fi
    login_msg $login_file
}

function setup_zsh() {
    # .zshenv is read in all types of shell
    # .zshrc is read in interactive shells 
    env_file=${HOME}/.zshenv
    login_file=${HOME}/.zshrc

    newfile $env_file ; env_msg $env_file

    newfile $login_file ; login_msg $login_file
}

setup_bash
setup_zsh

unset newfile fprint env_file env_msg setup_bash setup_zsh
