#!/bin/bash

zshrc=${HOME}/.zshrc
zshenv=${HOME}/.zshenv
[ -n $DOTFILE_PATH ] && export DOTFILE_PATH=${HOME}/.dotfile
dotfile_env=${DOTFILE_PATH}/env.zsh
dotfile_rc=${DOTFILE_PATH}/rc.zsh

function __install_file() {
    new_file=$1
    if [ -f $new_file ]; then
        backup_path=$DOTFILE_PATH/Data/backups/${new_file}_$(date | sed s/\ /_/g)
        echo "Moving original $new_file as $backup_path"
        mv $new_file $backup_path
    fi
    
    touch $new_file
}

function __fprint() {
    file=$1
    shift
    echo "# File generated by 'dotfile'" >> $file
    for message in $@; do
        echo $message >> $file
    done
}


__install_file $zshenv

__fprint $zshenv \
"export DOTFILE_PATH=${DOTFILE_PATH}" \
"#" "#" \
"# This will shource zshenv script in 'dotfile'" \
"source ${dotfile_env}" \
"#" "#" \
"#############################################" \
"# User settings" \
"" "" \
"#############################################"

__install_file $zshrc

__fprint $zshrc "source ${dotfile_rc}" \
"#############################################" \
"# User settings:" \
"" "" \
"#############################################"

source $zshrc

echo "Setup complete"
echo "Restart zsh session for changes to take full effect."

unset dotfile_env dotfile_rc __install_file __fprint

# # TODO: Source dependencies
# if [ -f $zshenv ]; then
#     zenv_backup=$DOTFILE_PATH/Data/file_backups/zshenv_$(date | sed s/\ /_/g)
#     echo "Copying original $zshenv to $zsh_backup"
#     cp $zshenv $zsh_backup
#     rm -f $zshenv
# fi

# echo "# \$DOTFILE defines the path for the directory of the zsh files." >> $zshenv
# echo "export DOTFILE_PATH=${DOTFILE_PATH}" >> $zshenv
# echo "#" >> $zshenv
# echo "#" >> $zshenv
# echo "source ${dotfile_env}" >> $zshenv

# # TODO: Source dependencies
# if [ -f $zshrc ]; then
#     zsh_backup=$DOTFILE_PATH/Data/zshrc_backups/zshrc_$(date | sed s/\ /_/g)
#     echo "Copying original $zshrc to $zsh_backup"
#     cp $zshrc $zsh_backup
#     rm -f $zshrc
# fi

# echo "# The content was automatically generated during installation of msoukharev/dotfiles." >> $zshrc
# echo "#" >> $zshrc
# echo "#" >> $zshrc

# echo "# This file is the entry script to the project. It will source all the dotfiles, scripts, plugins and configs contained in ${DOTFILE_PATH} directory." >> $zshrc
# echo "source ${dotfile_rc}" >> $zshrc
# echo "#" >> $zshrc
# echo "#" >> $zshrc

# echo "#############################################" >> $zshrc
# echo "# User settings:" >> $zshrc
# echo "#############################################" >> $zshrc

# source $zshrc

# echo "Setup complete"
# echo "Restart zsh session for changes to take full effect."

# unset dotfile_rc