#!/bin/bash

# Set default directory for the path
[ -n $DOTFILE_PATH ] && export DOTFILE_PATH=${HOME}/.dotfile

# Source environment scripts
for file in $(ls $DOTFILE_PATH/env); do
    source ${DOTFILE_PATH}/env/${file}
done

source_env=${DOTFILE_PATH}/source_env.bash
source_login=${DOTFILE_PATH}/source_login.bash

# Creates a file and puts an existing file into a backup directory
function newfile() {
    new_file=$1
    if [ -f $new_file ]; then
        backup_dir=$DOTFILE_PATH/data/backups
        mkdir -p $backup_dir >/dev/null 2>&1
        backup_file=$backup_dir/$(basename $new_file)_$(date | sed s/\ /_/g)
        echo -e "Moving original $new_file as: \n $backup_file\n"
        mv $new_file $backup_file
    fi
    touch $new_file
}

# Appends 2..> arguments as lines of text to a file
function fprint() {
    file=$1
    shift
    msgs=("$@")
    echo "# File generated by 'dotfile'" >> $file
    for arg; do
        echo "$arg" >> $file
    done
}

# This autogenerated text will be placed in non-interactive startup files
function env_msg() {
    file=$1
    fprint $file \
    "export DOTFILE_PATH=${DOTFILE_PATH}" \
    "#" \
    "source ${source_env}" \
    "#" \
    "#" \
    "#############################################" \
    "" \
    "# User settings:" \
    "#" \
    "#" \
    "#############################################"
}

# This autogenerated text will be placed in interactive startup files
function login_msg() {
    file=$1
    fprint $file \
    "# You can change themes to default ones in ${DOTFILE_PATH}/themes." \
    "# You can also add your own themes to ${DOTFILE_PATH}/themes/user." \
    "# Use theme filename as the value" \
    "#" \
    "theme=default" \
    "#" \
    "source ${source_login}" \
    "#" \
    "#" \
    "#############################################" \
    "#" \
    "# User settings:" \
    "#" \
    "#" \
    "#############################################"
}

function setup_bash() {
    env_file=${HOME}/.bashrc
    newfile $env_file
    fprint $env_file "export BASH_ENV=$env_file"
    env_msg $env_file

    login_file=${HOME}/.bash_profile
    [ -f $login_file ] || touch $login_file
    newfile $login_file
    # We want to source .bashrc in .bash_profile
    # Some systems do not source it when starting a login shell
    fprint $login_file "[ -f ${HOME}/.bashrc ] && source ${HOME}/.bashrc"
    # Some linux systems come with a default `.profile` having valuable stuff in it
    __linux && fprint $login_file "[ -f ${HOME}/.profile ] && source ${HOME}/.profile"
    login_msg $login_file
}

function setup_zsh() {
    # .zshenv is read in all types of shell
    # .zshrc is read in interactive shells 
    env_file=${HOME}/.zshenv
    login_file=${HOME}/.zshrc

    newfile $env_file ; env_msg $env_file

    newfile $login_file ; login_msg $login_file
}

setup_bash
setup_zsh

unset newfile fprint env_file env_msg setup_bash setup_zsh
