#!/bin/bash

zshrc=${HOME}/.zshrc
zshenv=${HOME}/.zshenv
[ -n $DOTFILE_PATH ] && export DOTFILE_PATH=${HOME}/.dotfile
dotfile_env=${DOTFILE_PATH}/env.zsh
dotfile_rc=${DOTFILE_PATH}/rc.zsh

function newfile() {
    new_file=$1
    if [ -f $new_file ]; then
        backup_path=$DOTFILE_PATH/Data/backups/$(basename $new_file)_$(date | sed s/\ /_/g)
        echo "Moving original $new_file as $backup_path"
        mv $new_file $backup_path
    fi
    
    touch $new_file
}

function fprint() {
    file=$1
    shift
    echo "# File generated by 'dotfile'" >> $file
    for message in $@; do
        echo $message >> $file
    done
}


newfile $zshenv

fprint $zshenv \
"export DOTFILE_PATH=${DOTFILE_PATH}" \
"#" "#" \
"# This script sources files in \$DOTFILE_PATH/Dotfiles/Env folder" \
"source ${dotfile_env}" \
"#" "#" \
"#############################################" \
"# User settings" \
"" "" \
"#############################################"

newfile $zshrc

fprint $zshrc \
"# This variable defines the theme to use with your shell" \
"# You can add your own themes to \$DOTFILE_PATH/Themes/User ..." \
"# ... and change the name of the variable to the file defining the theme" \
"theme=default" \
"#" "#" \
"# This script sources files in \$DOTFILE_PATH/Dotfiles/Env folder" \
"source ${dotfile_rc}" \
"#" "#" \
"#############################################" \
"# User settings:" \
"" "" \
"#############################################"

source $zshrc

echo "Setup complete"
echo "Restart zsh session for changes to take full effect."

unset dotfile_env dotfile_rc newfile fprint
